"""T-171/T-173: deep-crisis backtest of a bought managed-futures sleeve.

Reproducible from the repo: fetches the free AQR TSMOM monthly factor from
the public URL, pulls the canonical base equity curve from S3, and computes
the deep-crisis (dotcom + GFC) combined-portfolio MDD A/B, net of the
gross->net haircut calibrated to RYMFX.

  python scripts/mf_sleeve_deep_crisis_t171.py

Data (gitignored; regenerated by this script):
  - AQR TSMOM monthly:
      https://www.aqr.com/-/media/AQR/Documents/Insights/Data-Sets/Time-Series-Momentum-Factors-Monthly.xlsx
    pinned snapshot sha256 prefix e75450e2 (AQR reconstructs history on each
    update; verify the sha or accept drift). Credit: AQR Capital Management, LLC.
  - Base curve (canonical 26yr arm0, T-128r/T-118r `158fe678`):
      s3://archondex-results-407539788432/t118r-v1-26yr/arm0_v1/26yr/rep1/
        3b403882-8ad5-4aba-a4c1-d1b15c8bce6f/portfolio_snapshots.csv

T-173 FIX: the original T-171 combined AQR and the base on the INTERSECTION
of their datetime indices and then dropped non-aligning rows. AQR's month-end
dates and the base resample('ME') month-end dates do not match day-for-day in
~7 of 24 GFC months, so dropna() silently removed those months -- including
the deep-trough months -- shallowing the combined MDD ~2x. The fix: align both
monthly series on calendar-month PERIODS (.to_period('M')) and combine on the
full window with NO dropna. Always assert mf-NaN-count == 0 over each window.
"""
from __future__ import annotations

import hashlib
import urllib.request
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
AQR_URL = ("https://www.aqr.com/-/media/AQR/Documents/Insights/Data-Sets/"
           "Time-Series-Momentum-Factors-Monthly.xlsx")
AQR_LOCAL = ROOT / "data/external/aqr/aqr_tsmom_monthly_snapshot_20260615.xlsx"
AQR_PINNED_SHA_PREFIX = "e75450e2"
BASE_S3 = ("s3://archondex-results-407539788432/t118r-v1-26yr/arm0_v1/26yr/"
           "rep1/3b403882-8ad5-4aba-a4c1-d1b15c8bce6f/portfolio_snapshots.csv")
BASE_LOCAL = ROOT / "data/external/base_curve/t118r_v1_26yr_arm0_3b403882.csv"

# Net GFC anchors for the haircut (RYMFX, fees-embedded, via yfinance — see
# T-171 audit). Hardcoded here as the calibration constants used; re-derive
# with yfinance if regenerating from scratch.
RYMFX_GFC_NET = 0.099       # 2007-07 -> 2009-06
RYMFX_2008CAL_NET = 0.068   # 2008 calendar

WINDOWS = {"dotcom": ("2000-01", "2002-12"), "GFC": ("2007-07", "2009-06")}
ALLOCS = [0.10, 0.20, 0.30]


def _ensure_aqr() -> Path:
    AQR_LOCAL.parent.mkdir(parents=True, exist_ok=True)
    if not AQR_LOCAL.exists():
        print(f"[t171] fetching AQR TSMOM from {AQR_URL}")
        urllib.request.urlretrieve(AQR_URL, AQR_LOCAL)
    sha = hashlib.sha256(AQR_LOCAL.read_bytes()).hexdigest()
    print(f"[t171] AQR snapshot sha256 {sha[:8]} (pinned {AQR_PINNED_SHA_PREFIX})"
          + ("" if sha.startswith(AQR_PINNED_SHA_PREFIX) else "  *** SHA DRIFT — AQR reconstructed history ***"))
    return AQR_LOCAL


def _ensure_base() -> Path:
    if not BASE_LOCAL.exists():
        import subprocess
        BASE_LOCAL.parent.mkdir(parents=True, exist_ok=True)
        print(f"[t171] pulling base curve from {BASE_S3}")
        subprocess.run(["aws", "s3", "cp", BASE_S3, str(BASE_LOCAL),
                        "--profile", "archondex", "--quiet"], check=True)
    return BASE_LOCAL


def load_aqr_monthly() -> pd.Series:
    x = pd.read_excel(_ensure_aqr(), sheet_name="TSMOM Factors", skiprows=17)
    x = x.rename(columns={x.columns[0]: "date"})
    x["date"] = pd.to_datetime(x["date"], errors="coerce")
    x = x.dropna(subset=["date"])
    s = x.set_index("date")["TSMOM"].astype(float)
    s.index = s.index.to_period("M")          # <-- the T-173 alignment fix
    return s


def load_base_monthly_returns() -> tuple[pd.Series, float]:
    b = pd.read_csv(_ensure_base())
    b["timestamp"] = pd.to_datetime(b["timestamp"])
    eq = b.sort_values("timestamp").set_index("timestamp")["equity"].astype(float)
    daily_mdd = float(((eq / eq.cummax()) - 1).min())
    mr = eq.resample("ME").last().pct_change().dropna()
    mr.index = mr.index.to_period("M")        # <-- the T-173 alignment fix
    return mr, daily_mdd


def mdd(r: pd.Series) -> float:
    eq = (1 + r).cumprod()
    return float(((eq - eq.cummax()) / eq.cummax()).min())


def cum(s: pd.Series, a: str, b: str) -> float:
    seg = s[(s.index >= a) & (s.index <= b)]
    return float((1 + seg).prod() - 1)


def main() -> int:
    aqr = load_aqr_monthly()
    bmr, daily_mdd = load_base_monthly_returns()
    assert abs(daily_mdd - (-0.3261)) < 1e-3, f"base daily MDD {daily_mdd:.4f} != -0.3261"

    # Haircut calibration (k so AQR window return matches RYMFX net)
    k_primary = RYMFX_GFC_NET / cum(aqr, "2007-07", "2009-06")
    k_consv = RYMFX_2008CAL_NET / cum(aqr, "2008-01", "2008-12")
    print(f"[t171] base daily MDD {daily_mdd*100:.2f}%  "
          f"haircut k_primary={k_primary:.3f} k_conservative={k_consv:.3f}")

    for wlbl, (a, e) in WINDOWS.items():
        bw = bmr[(bmr.index >= a) & (bmr.index <= e)]
        bmdd = mdd(bw)
        print(f"\n=== {wlbl} {a}..{e} ({len(bw)} mo)  base MDD {bmdd*100:.2f}% ===")
        for kl, k in [("k=.711", k_primary), ("k=.278", k_consv)]:
            mf = (aqr * k).reindex(bw.index)
            assert mf.isna().sum() == 0, f"{wlbl} {kl}: {mf.isna().sum()} unaligned months — alignment bug"
            for x in ALLOCS:
                c = (1 - x) * bw + x * mf            # full window, NO dropna
                m = mdd(c)
                red = (abs(bmdd) - abs(m)) / abs(bmdd) * 100
                print(f"   {kl} base+{int(x*100)}%: MDD {m*100:6.1f}%  cut {red:4.0f}%"
                      + ("  [>=25%]" if red >= 25 else "  [<25%]"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
